# Generated by Django 3.0.2 on 2020-09-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_data',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
