# Generated by Django 3.0.2 on 2020-09-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0002_leave_data_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_data',
            name='total_leaves_left',
        ),
    ]
