# Generated by Django 3.0.2 on 2020-09-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mob_no',
        ),
        migrations.AddField(
            model_name='user',
            name='emp_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
