# Generated by Django 3.0.2 on 2020-09-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200901_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_leaves_left',
            field=models.IntegerField(default=0),
        ),
    ]
